# Generated by Django 3.0.5 on 2025-03-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volton', '0011_auto_20250301_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtr',
            options={'ordering': ('-created',), 'verbose_name': 'Haberler', 'verbose_name_plural': 'Haberler'},
        ),
        migrations.AlterModelOptions(
            name='keywordstr',
            options={'ordering': ('-created',), 'verbose_name': 'Keywords', 'verbose_name_plural': 'Keywords'},
        ),
    ]
