# Generated by Django 3.0.5 on 2025-03-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volton', '0012_auto_20250306_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bros',
            options={'ordering': ('-created',), 'verbose_name': 'Broşür', 'verbose_name_plural': 'Broşürler'},
        ),
        migrations.AlterModelOptions(
            name='iletisim',
            options={'ordering': ('-created',), 'verbose_name': 'Mesaj', 'verbose_name_plural': 'Gelen Mesajlar'},
        ),
        migrations.AlterModelOptions(
            name='productstr',
            options={'ordering': ('-created',), 'verbose_name': 'Gazlar ve Ekipmanlar', 'verbose_name_plural': 'Gazlar ve Ekipmanlar'},
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='certifica',
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='kullanim',
        ),
    ]
