# Generated by Django 3.0.5 on 2025-03-09 20:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volton', '0013_auto_20250309_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim')),
                ('tek_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Özellikler')),
                ('slug', models.SlugField(max_length=100)),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Description')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='volton.KeywordsTR', verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Endüstriler',
                'verbose_name_plural': 'Endüstriler',
                'ordering': ('-created',),
            },
        ),
    ]
