# Generated by Django 3.0.5 on 2025-03-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volton', '0014_industries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industries',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productstr',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
